import { v4 as uuid } from 'uuid'

let inventory = [
  {
    categories: ['lancamentos', 'sofa'], name: 'Timber Gray Sofa 2.0', price: '1000', image: '/products/couch1.png', description: 'Fique um pouco. O sofá Timber charme chocolat está situado em cima de um acabamento em carvalho e exibe almofadas de assento e encosto de couro macio. Com o tempo, o estofamento totalmente anilina deste sofá de couro marrom desenvolverá uma aparência vintage desgastada. Aconchegue-se com sua gracinha (animal ou humana) e mergulhe em uma tigela de pipoca. Este sofá é realmente difícil de sair. Variações de cores naturais, rugas e vincos fazem parte das características únicas desse couro. Ele desenvolverá um visual vintage descontraído com uso regular.', brand: 'Jason Bourne', currentInventory: 4 },
    
  {
    categories: ['on sale', 'sofa'], name: 'Sven Tan Matte', price: '1200', image: '/products/couch8.png', description: 'Você não precisa sair para ser resistente. O sofá de couro cru Cigar apresenta uma estrutura robusta de madeira com cantos bloqueados e costuras brutas para aquele visual de Malboro. Este sofá de couro marrom é aconchegante em uma casa de campo, cabana ou condomínio. E o couro (o couro!) fica mais bonito com o uso: marcas sutis de caracteres como picadas de insetos, cicatrizes cicatrizadas e variação de grão refletem uma verdadeira safra. Prepare-se e passe o controle remoto.', brand: 'Jason Bourne' , currentInventory: 7 },
  {
    categories: ['on sale', 'sofa'], name: 'Otis Malt Sofa', price: '500', image: '/products/couch9.png', description: 'Você não precisa sair para ser resistente. O sofá de couro cru Cigar apresenta uma estrutura robusta de madeira com cantos bloqueados e costuras brutas para aquele visual de Malboro. Este sofá de couro marrom é aconchegante em uma casa de campo, cabana ou condomínio. E o couro (o couro!) fica mais bonito com o uso: marcas sutis de caracteres como picadas de insetos, cicatrizes cicatrizadas e variação de grão refletem uma verdadeira safra. Prepare-se e passe o controle remoto.' , brand: 'Jason Bourne', currentInventory: 13},
  {
    categories: ['on sale', 'sofa'], name: 'Ceni Brown 3 Seater', price: '650', image: '/products/couch10.png', description: 'Você não precisa sair para ser resistente. O sofá de couro cru Cigar apresenta uma estrutura robusta de madeira com cantos bloqueados e costuras brutas para aquele visual de Malboro. Este sofá de couro marrom é aconchegante em uma casa de campo, cabana ou condomínio. E o couro (o couro!) fica mais bonito com o uso: marcas sutis de caracteres como picadas de insetos, cicatrizes cicatrizadas e variação de grão refletem uma verdadeira safra. Prepare-se e passe o controle remoto.' , brand: 'Jason Bourne', currentInventory: 9},
  {
    categories: ['venda', 'sofa'], name: 'Jameson Jack Lounger', price: '1230', image: '/products/couch11.png', description: 'Você não precisa sair para ser resistente. O sofá de couro cru Cigar apresenta uma estrutura robusta de madeira com cantos bloqueados e costuras brutas para aquele visual de Malboro. Este sofá de couro marrom é aconchegante em uma casa de campo, cabana ou condomínio. E o couro (o couro!) fica mais bonito com o uso: marcas sutis de caracteres como picadas de insetos, cicatrizes cicatrizadas e variação de grão refletem uma verdadeira safra. Prepare-se e passe o controle remoto.', brand: 'Jason Bourne', currentInventory: 24 },

  {
    categories: ['on sale', 'sofa'], name: 'Dabit Matte Black', price: '1200', image: '/products/couch4.png', description: 'Você não precisa sair para ser resistente. O sofá de couro cru Cigar apresenta uma estrutura robusta de madeira com cantos bloqueados e costuras brutas para aquele visual de Malboro. Este sofá de couro marrom é aconchegante em uma casa de campo, cabana ou condomínio. E o couro (o couro!) fica mais bonito com o uso: marcas sutis de caracteres como picadas de insetos, cicatrizes cicatrizadas e variação de grão refletem uma verdadeira safra. Prepare-se e passe o controle remoto.', currentInventory: 14 },

  {
    categories: ['venda', 'cadeiras'], name: 'Embrace Blue', price: '300', image: '/products/chair1.png', description: 'Você não precisa sair para ser resistente. O sofá de couro cru Cigar apresenta uma estrutura robusta de madeira com cantos bloqueados e costuras brutas para aquele visual de Malboro. Este sofá de couro marrom é aconchegante em uma casa de campo, cabana ou condomínio. E o couro (o couro!) fica mais bonito com o uso: marcas sutis de caracteres como picadas de insetos, cicatrizes cicatrizadas e variação de grão refletem uma verdadeira safra. Prepare-se e passe o controle remoto.' , brand: 'Jason Bourne', currentInventory: 12 },
  {
    categories: ['venda', 'cadeiras'], name: 'Nord Lounger', price: '825', image: '/products/chair2.png', description: 'Você não precisa sair para ser resistente. O sofá de couro cru Cigar apresenta uma estrutura robusta de madeira com cantos bloqueados e costuras brutas para aquele visual de Malboro. Este sofá de couro marrom é aconchegante em uma casa de campo, cabana ou condomínio. E o couro (o couro!) fica mais bonito com o uso: marcas sutis de caracteres como picadas de insetos, cicatrizes cicatrizadas e variação de grão refletem uma verdadeira safra. Prepare-se e passe o controle remoto.' , brand: 'Jason Bourne', currentInventory: 13},
  {
    categories: ['venda', 'cadeiras'], name: 'Ceni Matte Oranve', price: '720', image: '/products/chair3.png', description: 'Você não precisa sair para ser resistente. O sofá de couro cru Cigar apresenta uma estrutura robusta de madeira com cantos bloqueados e costuras brutas para aquele visual de Malboro. Este sofá de couro marrom é aconchegante em uma casa de campo, cabana ou condomínio. E o couro (o couro!) fica mais bonito com o uso: marcas sutis de caracteres como picadas de insetos, cicatrizes cicatrizadas e variação de grão refletem uma verdadeira safra. Prepare-se e passe o controle remoto.' , brand: 'Jason Bourne', currentInventory: 33},
  {
    categories: ['venda', 'cadeiras'], name: 'Abisko Green Recliner', price: '2000', image: '/products/chair4.png', description: 'Você não precisa sair para ser resistente. O sofá de couro cru Cigar apresenta uma estrutura robusta de madeira com cantos bloqueados e costuras brutas para aquele visual de Malboro. Este sofá de couro marrom é aconchegante em uma casa de campo, cabana ou condomínio. E o couro (o couro!) fica mais bonito com o uso: marcas sutis de caracteres como picadas de insetos, cicatrizes cicatrizadas e variação de grão refletem uma verdadeira safra. Prepare-se e passe o controle remoto.', brand: 'Fortunato Tapecaria', currentInventory: 23 },
  { categories: ['venda', 'cadeiras'], name: 'Denim on Denim Single', price: '1100', image: '/products/chair5.png', description: 'Você não precisa sair para ser resistente. O sofá de couro cru Cigar apresenta uma estrutura robusta de madeira com cantos bloqueados e costuras brutas para aquele visual de Malboro. Este sofá de couro marrom é aconchegante em uma casa de campo, cabana ou condomínio. E o couro (o couro!) fica mais bonito com o uso: marcas sutis de caracteres como picadas de insetos, cicatrizes cicatrizadas e variação de grão refletem uma verdadeira safra. Prepare-se e passe o controle remoto.' , brand: 'Pico de Jaca', currentInventory: 13},
  { categories: ['venda', 'cadeiras'], name: 'Levo Tan Lounge Chair', price: '600', image: '/products/chair6.png', description: 'Você não precisa sair para ser resistente. O sofá de couro cru Cigar apresenta uma estrutura robusta de madeira com cantos bloqueados e costuras brutas para aquele visual de Malboro. Este sofá de couro marrom é aconchegante em uma casa de campo, cabana ou condomínio. E o couro (o couro!) fica mais bonito com o uso: marcas sutis de caracteres como picadas de insetos, cicatrizes cicatrizadas e variação de grão refletem uma verdadeira safra. Prepare-se e passe o controle remoto.', brand: 'Jason Bourne', currentInventory: 15 },

  { categories: ['venda', 'cadeiras'], name: 'Anime Tint Recliner', price: '775', image: '/products/chair7.png', description: 'Você não precisa sair para ser resistente. O sofá de couro cru Cigar apresenta uma estrutura robusta de madeira com cantos bloqueados e costuras brutas para aquele visual de Malboro. Este sofá de couro marrom é aconchegante em uma casa de campo, cabana ou condomínio. E o couro (o couro!) fica mais bonito com o uso: marcas sutis de caracteres como picadas de insetos, cicatrizes cicatrizadas e variação de grão refletem uma verdadeira safra. Prepare-se e passe o controle remoto.', brand: 'Jason Bourne', currentInventory: 44 },
  { categories: ['venda', 'cadeiras'], name: 'Josh Jones Red Chair', price: '1200', image: '/products/chair8.png', description: 'Você não precisa sair para ser resistente. O sofá de couro cru Cigar apresenta uma estrutura robusta de madeira com cantos bloqueados e costuras brutas para aquele visual de Malboro. Este sofá de couro marrom é aconchegante em uma casa de campo, cabana ou condomínio. E o couro (o couro!) fica mais bonito com o uso: marcas sutis de caracteres como picadas de insetos, cicatrizes cicatrizadas e variação de grão refletem uma verdadeira safra. Prepare-se e passe o controle remoto.', brand: 'Jason Bourne', currentInventory: 17 },
  { categories: ['venda', 'cadeiras'], name: 'Black Sand Lounge', price: '1600', image: '/products/chair9.png', description: 'Você não precisa sair para ser resistente. O sofá de couro cru Cigar apresenta uma estrutura robusta de madeira com cantos bloqueados e costuras brutas para aquele visual de Malboro. Este sofá de couro marrom é aconchegante em uma casa de campo, cabana ou condomínio. E o couro (o couro!) fica mais bonito com o uso: marcas sutis de caracteres como picadas de insetos, cicatrizes cicatrizadas e variação de grão refletem uma verdadeira safra. Prepare-se e passe o controle remoto.', brand: 'Jason Bourne', currentInventory: 28 },
  { categories: ['venda', 'cadeiras'], name: 'Mint Beige Workchair', price: '550', image: '/products/chair10.png', description: 'Você não precisa sair para ser resistente. O sofá de couro cru Cigar apresenta uma estrutura robusta de madeira com cantos bloqueados e costuras brutas para aquele visual de Malboro. Este sofá de couro marrom é aconchegante em uma casa de campo, cabana ou condomínio. E o couro (o couro!) fica mais bonito com o uso: marcas sutis de caracteres como picadas de insetos, cicatrizes cicatrizadas e variação de grão refletem uma verdadeira safra. Prepare-se e passe o controle remoto.', brand: 'Jason Bourne', currentInventory: 31 },  
  { categories: ['teste', 'cadeiras'], name: 'Hakuna Matata', price: '777', image: '/products/chair10.png', description: 'Você não precisa sair para ser resistente. O sofá de couro cru Cigar apresenta uma estrutura robusta de madeira com cantos bloqueados e costuras brutas para aquele visual de Malboro. Este sofá de couro marrom é aconchegante em uma casa de campo, cabana ou condomínio. E o couro (o couro!) fica mais bonito com o uso: marcas sutis de caracteres como picadas de insetos, cicatrizes cicatrizadas e variação de grão refletem uma verdadeira safra. Prepare-se e passe o controle remoto.', brand: 'André Lobo', currentInventory: 88 }, 
 
]

inventory.map(i => {
  i.id = uuid()
  return i
})

export default inventory