import { v4 as uuid } from 'uuid'

let inventory = [
  {
    categories: ['chaise', 'sofa'], name: 'Sofá Chaise Inca', price: '800', image: '/products/sofa_chaise_inca.png', description: 'Fique um pouco. O sofá Timber charme chocolat está situado em cima de um acabamento em carvalho e exibe almofadas de assento e encosto de couro macio. Com o tempo, o estofamento totalmente anilina deste sofá de couro marrom desenvolverá uma aparência vintage desgastada. Aconchegue-se com sua gracinha (animal ou humana) e mergulhe em uma tigela de pipoca. Este sofá é realmente difícil de sair. Variações de cores naturais, rugas e vincos fazem parte das características únicas desse couro. Ele desenvolverá um visual vintage descontraído com uso regular.', brand: 'Fortunato Tapeçaria', currentInventory: 4 },
    
  {
    categories: ['chaise', 'sofa'], name: 'Sofa Chaise Salmon', price: '800', image: '/products/sofa_chaise_salmon2.png', description: 'Você não precisa sair para ser resistente. O sofá de couro cru Cigar apresenta uma estrutura robusta de madeira com cantos bloqueados e costuras brutas para aquele visual de Malboro. Este sofá de couro marrom é aconchegante em uma casa de campo, cabana ou condomínio. E o couro (o couro!) fica mais bonito com o uso: marcas sutis de caracteres como picadas de insetos, cicatrizes cicatrizadas e variação de grão refletem uma verdadeira safra. Prepare-se e passe o controle remoto.', brand: 'Fortunato Tapeçaria' , currentInventory: 7 },
  {
    categories: ['sob medida', 'sofa'], name: 'Sofás sob medida', price: '2900', image: '/products/sofa_retratil_reclibável12.png', description: 'Você não precisa sair para ser resistente. O sofá de couro cru Cigar apresenta uma estrutura robusta de madeira com cantos bloqueados e costuras brutas para aquele visual de Malboro. Este sofá de couro marrom é aconchegante em uma casa de campo, cabana ou condomínio. E o couro (o couro!) fica mais bonito com o uso: marcas sutis de caracteres como picadas de insetos, cicatrizes cicatrizadas e variação de grão refletem uma verdadeira safra. Prepare-se e passe o controle remoto.' , brand: 'Fortunato Tapeçaria', currentInventory: 13},
  {
    categories: ['chaise', 'sofa'], name: 'Sofá Chaise Branco', price: '800', image: '/products/sofa_chaise_branco.png', description: 'Você não precisa sair para ser resistente. O sofá de couro cru Cigar apresenta uma estrutura robusta de madeira com cantos bloqueados e costuras brutas para aquele visual de Malboro. Este sofá de couro marrom é aconchegante em uma casa de campo, cabana ou condomínio. E o couro (o couro!) fica mais bonito com o uso: marcas sutis de caracteres como picadas de insetos, cicatrizes cicatrizadas e variação de grão refletem uma verdadeira safra. Prepare-se e passe o controle remoto.' , brand: 'Fortunato Tapeçaria', currentInventory: 9},
  {
    categories: ['de canto', 'sofa'], name: 'Sofá de canto em L', price: '2900', image: '/products/sofaele1_vermelho.png', description: 'Você não precisa sair para ser resistente. O sofá de couro cru Cigar apresenta uma estrutura robusta de madeira com cantos bloqueados e costuras brutas para aquele visual de Malboro. Este sofá de couro marrom é aconchegante em uma casa de campo, cabana ou condomínio. E o couro (o couro!) fica mais bonito com o uso: marcas sutis de caracteres como picadas de insetos, cicatrizes cicatrizadas e variação de grão refletem uma verdadeira safra. Prepare-se e passe o controle remoto.', brand: 'Fortunato Tapeçaria', currentInventory: 24 },

  {
    categories: ['de canto', 'sofa'], name: 'Sofá de canto em L vinho', price: '2900', image: '/products/sofa_de_canto_vinho.png', description: 'Você não precisa sair para ser resistente. O sofá de couro cru Cigar apresenta uma estrutura robusta de madeira com cantos bloqueados e costuras brutas para aquele visual de Malboro. Este sofá de couro marrom é aconchegante em uma casa de campo, cabana ou condomínio. E o couro (o couro!) fica mais bonito com o uso: marcas sutis de caracteres como picadas de insetos, cicatrizes cicatrizadas e variação de grão refletem uma verdadeira safra. Prepare-se e passe o controle remoto.', currentInventory: 14 },

  {
    categories: ['chaise', 'sofa'], name: 'Sofá Chaise Marrom', price: '800', image: '/products/sofa_chaise_marrom.png', description: 'Você não precisa sair para ser resistente. O sofá de couro cru Cigar apresenta uma estrutura robusta de madeira com cantos bloqueados e costuras brutas para aquele visual de Malboro. Este sofá de couro marrom é aconchegante em uma casa de campo, cabana ou condomínio. E o couro (o couro!) fica mais bonito com o uso: marcas sutis de caracteres como picadas de insetos, cicatrizes cicatrizadas e variação de grão refletem uma verdadeira safra. Prepare-se e passe o controle remoto.' , brand: 'Fortunato Tapeçaria', currentInventory: 12 },
  {
    categories: ['chaise', 'sofa'], name: 'Sofá Chaise Amarelo', price: '800', image: '/products/sofa_chaise_amarelo.png', description: 'Você não precisa sair para ser resistente. O sofá de couro cru Cigar apresenta uma estrutura robusta de madeira com cantos bloqueados e costuras brutas para aquele visual de Malboro. Este sofá de couro marrom é aconchegante em uma casa de campo, cabana ou condomínio. E o couro (o couro!) fica mais bonito com o uso: marcas sutis de caracteres como picadas de insetos, cicatrizes cicatrizadas e variação de grão refletem uma verdadeira safra. Prepare-se e passe o controle remoto.' , brand: 'Fortunato Tapeçaria', currentInventory: 13},
  {
    categories: ['chaise', 'sofa'], name: 'Sofá Chaise Inca Bronze', price: '800', image: '/products/sofa_chaise_inca_bronze.png', description: 'Você não precisa sair para ser resistente. O sofá de couro cru Cigar apresenta uma estrutura robusta de madeira com cantos bloqueados e costuras brutas para aquele visual de Malboro. Este sofá de couro marrom é aconchegante em uma casa de campo, cabana ou condomínio. E o couro (o couro!) fica mais bonito com o uso: marcas sutis de caracteres como picadas de insetos, cicatrizes cicatrizadas e variação de grão refletem uma verdadeira safra. Prepare-se e passe o controle remoto.' , brand: 'Fortunato Tapeçaria', currentInventory: 33},
  {
    categories: ['poltrona', 'poltrona'], name: 'Poltrona Cinza', price: '500', image: '/products/poltrona_cinza.png', description: 'Você não precisa sair para ser resistente. O sofá de couro cru Cigar apresenta uma estrutura robusta de madeira com cantos bloqueados e costuras brutas para aquele visual de Malboro. Este sofá de couro marrom é aconchegante em uma casa de campo, cabana ou condomínio. E o couro (o couro!) fica mais bonito com o uso: marcas sutis de caracteres como picadas de insetos, cicatrizes cicatrizadas e variação de grão refletem uma verdadeira safra. Prepare-se e passe o controle remoto.', brand: 'Fortunato Tapecaria', currentInventory: 23 },
  {
    categories: ['chaise', 'poltrona'], name: 'Sofá Chaise Preto', price: '800', image: '/products/sofa_chaise_preto.png', description: 'Você não precisa sair para ser resistente. O sofá de couro cru Cigar apresenta uma estrutura robusta de madeira com cantos bloqueados e costuras brutas para aquele visual de Malboro. Este sofá de couro marrom é aconchegante em uma casa de campo, cabana ou condomínio. E o couro (o couro!) fica mais bonito com o uso: marcas sutis de caracteres como picadas de insetos, cicatrizes cicatrizadas e variação de grão refletem uma verdadeira safra. Prepare-se e passe o controle remoto.', brand: 'Fortunato Tapecaria', currentInventory: 37 },
  
 
]

inventory.map(i => {
  i.id = uuid()
  return i
})

export default inventory